/** Dictionary namespace owned by this plugin. */
export const NS = "dsh-skins.ui";

/**
 * UI dictionaries. `zh` is the key-set source of truth; `en` must stay
 * key-complete against it (tests/dicts.test.mjs enforces this in both
 * directions, including `{placeholder}` parity).
 */
export const DICTS = {
  zh: {
    "skins.switch": "皮肤切换",
    "skins.title": "选择皮肤",
    "skins.official.label": "DeepSeek Harness（官方）",
    "skins.official.description": "还其正印 · 素卷玄青 · 一如本貌",
    "appearance.title": "外观配色",
    "appearance.light": "浅色",
    "appearance.dark": "深色",
    "appearance.system": "跟随系统",
    "update.checking": "正在检查更新…",
    "update.checkFailed": "暂时无法检查更新",
    "update.retry": "重试",
    "update.developmentCurrent": "本地开发模式 - v{current}（最新正式版 v{latest}）",
    "update.developmentNewer": "本地开发模式 - v{current}（可更新至 v{latest}）",
    "update.unsupported": "当前安装来源不支持在线更新",
    "update.unsupportedHint": "仅从官方 GitHub 仓库安装的版本可以一键更新",
    "update.available": "发现插件更新",
    "update.versions": "v{current} → v{latest}",
    "update.releaseNotes": "查看版本说明",
    "update.action": "更新",
    "update.failed": "更新失败",
    "update.installed": "更新已安装",
    "update.restartRequired": "v{version} 将在重启 DSH Web 后生效",
    "update.restartNow": "立即重启",
    "update.confirmRestart": "确认重启",
    "update.confirmUnknown": "仍要重启",
    "update.later": "稍后",
    "update.deferred": "已选择稍后重启",
    "update.restartManual": "请手动重启 DSH Web",
    "update.restarting": "正在重启…",
    "update.restart.blocked": "检测到 {count} 个 Agent 正在运行，请稍后重试",
    "update.restart.unknown": "无法确认 Agent 状态；再次点击“仍要重启”表示你确认继续",
    "update.phase.queued": "更新已排队",
    "update.phase.checking": "正在检查最新正式版本…",
    "update.phase.preparing": "正在验证 Release…",
    "update.phase.installing": "正在下载安装…",
    "update.phase.validating": "正在校验安装结果…",
    "update.phase.rollback": "更新失败，正在恢复原版本…",
    // Personalization surface (1.0.0)
    "personalization.title": "个性化",
    "personalization.reset": "恢复默认",
    "personalization.resetJoin": "、",
    "personalization.resetConfirm": "以下设置将恢复为出厂默认：\n{fields}\n此操作立即生效，确认继续吗？",
    "personalization.light": "浅色",
    "personalization.dark": "深色",
    "personalization.builtin": "内置画作",
    "personalization.builtin.default": "默认壁纸",
    "personalization.wallpaper": "壁纸",
    "personalization.slogan": "标语",
    "personalization.panelTranslucency": "面板通透度",
    "personalization.tgcf.crimson": "花城 · 银蝶灯笼",
    "personalization.tgcf.pale": "谢怜 · 云海宫阙",
    "personalization.library": "图库",
    "personalization.library.upload": "上传图片",
    "personalization.library.delete": "删除",
    "personalization.library.deleteConfirm": "删除后，以下皮肤的壁纸将回退为默认：",
    "personalization.library.deleteFailed": "删除失败，请重试",
    "personalization.library.deleted": "已删除：{name}",
    "personalization.library.empty": "图库为空，上传一张图片试试",
    "personalization.library.more": "还有 {count} 张未显示",
    "personalization.panelLabel": "个性化设置",
    "personalization.saveFailed": "保存失败，请重试",
    "personalization.library.clear": "清空图库",
    "personalization.library.clearConfirm": "将永久删除全部 {count} 张上传图片，且不可恢复。以下壁纸设置将回退为默认：{names}",
    "personalization.library.clearFailed": "部分图片删除失败，已刷新剩余列表",
    "personalization.library.uploading": "正在上传…",
    "personalization.status.loading": "正在同步个性化配置…",
    "personalization.status.offline": "配置尚未同步，暂时无法编辑",
    "personalization.status.retry": "重试",
    "personalization.status.unsupported": "配置由更新版本的插件创建，当前只读",
    "personalization.status.recovery": "检测到配置文件损坏",
    "personalization.status.recoveryHint": "可以从图片库重建配置；自定义标语与颜色等覆写可能丢失。",
    "personalization.recovery.confirm": "确认恢复",
    // Host-reported personalization errors (see HOST_ERROR_KEYS)
    "host.personalization.tooLarge": "图片超过大小限制",
    "host.personalization.unsupportedImage": "不支持的图片格式",
    "host.personalization.animatedWebp": "动画 WebP 暂不支持",
    "host.personalization.diskFull": "磁盘剩余空间不足",
    "host.personalization.invalidFilename": "文件展示名无效",
    "host.personalization.assetMissing": "图片不存在",
    "host.personalization.invalidConfig": "配置校验失败",
    "host.personalization.readonly": "配置为更高版本创建，当前只读",
    "host.personalization.recoveryRequired": "配置状态待恢复，请先在个性化面板确认恢复",
    "host.personalization.unknownSkin": "皮肤不存在",
    // Host-reported errors, keyed by the stable `code` the Host attaches to
    // every user-facing error (see HOST_ERROR_KEYS). The Host keeps a zh
    // fallback message; the client renders the localized template instead.
    "host.restart.unavailable": "当前 DSH Host 不支持自重启",
    "host.restart.noPending": "当前没有等待重启应用的更新",
    "host.update.linkProtected": "本地 link 开发模式不会被在线更新覆盖",
    "host.update.sourceUnsupported": "当前安装来源不支持一键更新",
    "host.update.alreadyLatest": "已经是最新正式版本",
    "host.update.sourceChanged": "更新开始前安装来源已变化，请重新打开皮肤切换器",
    "host.update.originUnresolved": "无法从当前 GitHub 安装或 lockfile 解析原版本 commit，已停止更新",
    "host.update.commandFailed": "DSH 插件更新失败（exit {exitCode}）：{output}",
    "host.update.commandTimeout": "DSH 插件更新超时",
    "host.update.rollbackSuffix": "；自动回滚失败：{reason}",
    "host.github.checkFailed": "GitHub 更新检查失败（HTTP {status}）",
    "host.github.rateLimited": "GitHub 更新检查失败（HTTP {status}）；GitHub 未认证请求额度已用完",
    "host.release.notStable": "GitHub latest release 不是正式版本",
    "host.release.tagInvalid": "Release tag 必须严格使用 vX.Y.Z：{tag}",
    "host.release.shaInvalid": "Release tag object 缺少有效 SHA",
    "host.release.shaMissing": "Release tag 未解析到完整 commit SHA",
    "host.release.packageMissing": "Release commit 缺少可读取的 package.json",
    "host.release.packageInvalid": "Release commit 的 package.json 无效",
    "host.release.manifestMissing": "Release 缺少 package.json",
    "host.release.nameMismatch": "Release 包名必须是 {expected}",
    "host.release.versionMismatch": "Release tag v{tag} 与包版本 {version} 不一致",
    "host.release.repoMismatch": "Release 仓库必须是 {repository}",
    "host.release.notWebPlugin": "Release 包不是 DSH Web 客户端插件",
    "host.release.noBundlePatch": "Release 包未声明 DSH bundle patch",
    "host.profile.notPinned": "profile 未固定到已验证的更新 commit",
    "host.profile.bundleMissing": "profile 未注册 dsh-skins bundle",
    "host.rollback.lockfileMismatch": "恢复后的 lockfile commit 校验失败",
    "host.rollback.bundleMissing": "恢复后的 bundle 注册校验失败",
  },
  en: {
    "skins.switch": "Skin Switcher",
    "skins.title": "Choose Skin",
    "skins.official.label": "DeepSeek Harness (Official)",
    "skins.official.description": "DeepSeek mark · default backdrop · brand palette",
    "appearance.title": "Appearance",
    "appearance.light": "Light",
    "appearance.dark": "Dark",
    "appearance.system": "System",
    "update.checking": "Checking for updates…",
    "update.checkFailed": "Unable to check for updates",
    "update.retry": "Retry",
    "update.developmentCurrent": "Local development mode - v{current} (latest release v{latest})",
    "update.developmentNewer": "Local development mode - v{current} (update available: v{latest})",
    "update.unsupported": "This install source cannot update online",
    "update.unsupportedHint": "One-click update is available only for installs from the official GitHub repository",
    "update.available": "Plugin update available",
    "update.versions": "v{current} → v{latest}",
    "update.releaseNotes": "Release notes",
    "update.action": "Update",
    "update.failed": "Update failed",
    "update.installed": "Update installed",
    "update.restartRequired": "v{version} will take effect after DSH Web restarts",
    "update.restartNow": "Restart now",
    "update.confirmRestart": "Confirm restart",
    "update.confirmUnknown": "Restart anyway",
    "update.later": "Later",
    "update.deferred": "Restart deferred",
    "update.restartManual": "Restart DSH Web manually",
    "update.restarting": "Restarting…",
    "update.restart.blocked": "{count} Agent(s) are running; try again later",
    "update.restart.unknown": "Agent status is unavailable; click Restart anyway again to confirm",
    "update.phase.queued": "Update queued",
    "update.phase.checking": "Checking the latest stable release…",
    "update.phase.preparing": "Verifying the Release…",
    "update.phase.installing": "Downloading and installing…",
    "update.phase.validating": "Validating the installation…",
    "update.phase.rollback": "Update failed; restoring the previous version…",
    // Personalization surface (1.0.0)
    "personalization.title": "Personalize",
    "personalization.reset": "Restore defaults",
    "personalization.resetJoin": ", ",
    "personalization.resetConfirm": "These settings will be reset to factory defaults:\n{fields}\nThis takes effect immediately. Continue?",
    "personalization.light": "Light",
    "personalization.dark": "Dark",
    "personalization.builtin": "Built-in artwork",
    "personalization.builtin.default": "Default wallpaper",
    "personalization.wallpaper": "Wallpaper",
    "personalization.slogan": "Slogan",
    "personalization.panelTranslucency": "Panel translucency",
    "personalization.tgcf.crimson": "Hua Cheng · Crimson & Butterflies",
    "personalization.tgcf.pale": "Xie Lian · Cloud Pavilion",
    "personalization.library": "Library",
    "personalization.library.upload": "Upload image",
    "personalization.library.delete": "Delete",
    "personalization.library.deleteConfirm": "These skins will fall back to their default wallpaper:",
    "personalization.library.deleted": "Deleted: {name}",
    "personalization.library.deleteFailed": "Delete failed; try again",
    "personalization.library.empty": "Library is empty — upload an image",
    "personalization.library.more": "{count} more hidden",
    "personalization.panelLabel": "Personalization settings",
    "personalization.saveFailed": "Save failed; try again",
    "personalization.library.clear": "Clear library",
    "personalization.library.clearConfirm": "This permanently deletes all {count} uploaded images. These wallpaper settings fall back to defaults: {names}",
    "personalization.library.clearFailed": "Some deletions failed; the remaining list was refreshed",
    "personalization.library.uploading": "Uploading…",
    "personalization.status.loading": "Syncing personalization…",
    "personalization.status.offline": "Settings not synced yet; editing is unavailable",
    "personalization.status.retry": "Retry",
    "personalization.status.unsupported": "Created by a newer plugin version; read-only",
    "personalization.status.recovery": "Configuration file is damaged",
    "personalization.status.recoveryHint": "It can be rebuilt from the image library; custom slogans and colors may be lost.",
    "personalization.recovery.confirm": "Confirm recovery",
    // Host-reported personalization errors (see HOST_ERROR_KEYS)
    "host.personalization.tooLarge": "Image exceeds the size limit",
    "host.personalization.unsupportedImage": "Unsupported image format",
    "host.personalization.animatedWebp": "Animated WebP is not supported",
    "host.personalization.diskFull": "Not enough disk space",
    "host.personalization.invalidFilename": "Invalid display name",
    "host.personalization.assetMissing": "Image not found",
    "host.personalization.invalidConfig": "Configuration failed validation",
    "host.personalization.readonly": "Created by a newer config version; read-only",
    "host.personalization.recoveryRequired": "Configuration needs recovery; confirm it in the personalization panel first",
    "host.personalization.unknownSkin": "Skin not found",
    "host.restart.unavailable": "This DSH Host cannot restart itself",
    "host.restart.noPending": "No update is waiting to be applied by a restart",
    "host.update.linkProtected": "Local link development installs are never overwritten by online updates",
    "host.update.sourceUnsupported": "The current install source does not support one-click updates",
    "host.update.alreadyLatest": "Already on the latest stable release",
    "host.update.sourceChanged": "The install source changed before the update started; reopen the skin switcher",
    "host.update.originUnresolved": "Could not resolve the installed commit from the GitHub spec or lockfile; update aborted",
    "host.update.commandFailed": "DSH plugin update failed (exit {exitCode}): {output}",
    "host.update.commandTimeout": "DSH plugin update timed out",
    "host.update.rollbackSuffix": "; automatic rollback failed: {reason}",
    "host.github.checkFailed": "GitHub update check failed (HTTP {status})",
    "host.github.rateLimited": "GitHub update check failed (HTTP {status}); unauthenticated GitHub API quota is exhausted",
    "host.release.notStable": "The GitHub latest release is not a stable version",
    "host.release.tagInvalid": "Release tag must be strictly vX.Y.Z: {tag}",
    "host.release.shaInvalid": "Release tag object is missing a valid SHA",
    "host.release.shaMissing": "Release tag did not resolve to a full commit SHA",
    "host.release.packageMissing": "The release commit has no readable package.json",
    "host.release.packageInvalid": "The release commit package.json is invalid",
    "host.release.manifestMissing": "Release package.json is missing",
    "host.release.nameMismatch": "Release package name must be {expected}",
    "host.release.versionMismatch": "Release tag v{tag} does not match package version {version}",
    "host.release.repoMismatch": "Release repository must be {repository}",
    "host.release.notWebPlugin": "Release package is not a DSH Web client plugin",
    "host.release.noBundlePatch": "Release package does not declare a DSH bundle patch",
    "host.profile.notPinned": "Profile is not pinned to the verified update commit",
    "host.profile.bundleMissing": "Profile does not register the dsh-skins bundle",
    "host.rollback.lockfileMismatch": "Restored lockfile failed commit verification",
    "host.rollback.bundleMissing": "Restored profile failed bundle registration verification",
  },
};

/**
 * Stable Host error code → dictionary key. Every user-facing Host error
 * carries `code` (and optionally `params`); the update panel renders the
 * localized template when the code is known and falls back to the Host's
 * message otherwise.
 */
export const HOST_ERROR_KEYS = {
  RESTART_UNAVAILABLE: "host.restart.unavailable",
  NO_PENDING_UPDATE: "host.restart.noPending",
  RESTART_SAFETY_UNKNOWN: "update.restart.unknown",
  AGENTS_RUNNING: "update.restart.blocked",
  UPDATE_LINK_PROTECTED: "host.update.linkProtected",
  UPDATE_SOURCE_UNSUPPORTED: "host.update.sourceUnsupported",
  UPDATE_ALREADY_LATEST: "host.update.alreadyLatest",
  UPDATE_SOURCE_CHANGED: "host.update.sourceChanged",
  UPDATE_ORIGIN_UNRESOLVED: "host.update.originUnresolved",
  UPDATE_COMMAND_FAILED: "host.update.commandFailed",
  UPDATE_COMMAND_TIMEOUT: "host.update.commandTimeout",
  GITHUB_CHECK_FAILED: "host.github.checkFailed",
  GITHUB_CHECK_RATE_LIMITED: "host.github.rateLimited",
  RELEASE_NOT_STABLE: "host.release.notStable",
  RELEASE_TAG_INVALID: "host.release.tagInvalid",
  RELEASE_SHA_INVALID: "host.release.shaInvalid",
  RELEASE_SHA_MISSING: "host.release.shaMissing",
  RELEASE_PACKAGE_MISSING: "host.release.packageMissing",
  RELEASE_PACKAGE_INVALID: "host.release.packageInvalid",
  RELEASE_MANIFEST_MISSING: "host.release.manifestMissing",
  RELEASE_NAME_MISMATCH: "host.release.nameMismatch",
  RELEASE_VERSION_MISMATCH: "host.release.versionMismatch",
  RELEASE_REPOSITORY_MISMATCH: "host.release.repoMismatch",
  RELEASE_NOT_WEB_PLUGIN: "host.release.notWebPlugin",
  RELEASE_NO_BUNDLE_PATCH: "host.release.noBundlePatch",
  PROFILE_NOT_PINNED: "host.profile.notPinned",
  PROFILE_BUNDLE_MISSING: "host.profile.bundleMissing",
  ROLLBACK_LOCKFILE_MISMATCH: "host.rollback.lockfileMismatch",
  ROLLBACK_BUNDLE_MISSING: "host.rollback.bundleMissing",
  UPLOAD_TOO_LARGE: "host.personalization.tooLarge",
  UNSUPPORTED_IMAGE: "host.personalization.unsupportedImage",
  ANIMATION_UNSUPPORTED: "host.personalization.animatedWebp",
  DISK_FULL: "host.personalization.diskFull",
  FILENAME_INVALID: "host.personalization.invalidFilename",
  ASSET_NOT_FOUND: "host.personalization.assetMissing",
  INVALID_CONFIG: "host.personalization.invalidConfig",
  STORE_READONLY: "host.personalization.readonly",
  STORE_RECOVERY_REQUIRED: "host.personalization.recoveryRequired",
  UNKNOWN_SKIN: "host.personalization.unknownSkin",
};

/**
 * Format helper shared by the switcher and the update panel: substitutes
 * `{name}` placeholders, leaving unknown ones untouched (mirrors the
 * official locale runtime's `translate` behaviour).
 */
export function formatTemplate(template, params = {}) {
  return Object.entries(params).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}
